name: Build, Scan & Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Run SonarCloud scan for security & quality
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
  
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: "sapna1217_microservice_Assignment"
        SONAR_ORGANIZATION: "sapna1217"
       

   
    # Step 3: Log in to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: sapna1217/auth-service:latest                 

    # Step 5: Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 6: Deploy to Azure Container App
    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ctse                   
        containerAppName: authservice                                   
        imageToDeploy: sapna1217/auth-service:latest        
        containerAppEnvironment: myContainerEnv           
